spring:
  application:
    name: ms-medicos
  datasource:
    url: jdbc:mysql://localhost:3306/db_medicos?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/