spring.application.name=ms-gateway
server.port=8080

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# CONFIGURACIÓN DE RUTAS
# Ruta para Inventario
spring.cloud.gateway.routes[0].id=ms-inventario
spring.cloud.gateway.routes[0].uri=lb://ms-inventario
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/productos/**

# Ruta para Recetas
spring.cloud.gateway.routes[1].id=ms-recetas
spring.cloud.gateway.routes[1].uri=lb://ms-recetas
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/recetas/**

# Ruta para Facturación
spring.cloud.gateway.routes[2].id=ms-facturacion
spring.cloud.gateway.routes[2].uri=lb://ms-facturacion
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/facturas/**