server:
  port: 8085

spring:
  application:
    name: ms-citas

  datasource:
    url: jdbc:mysql://localhost:3306/db_citas?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  override-with-generic-response: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
