server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
# 🌟 ESTA SECCIÓN SE ACTIVARÁ SÓLO CUANDO CORRA EN DOCKER
spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    hostname: eureka-hospital