server:
  port: 8084

spring:
  application:
    name: ms-pacientes

  datasource:
    url: jdbc:mysql://localhost:3306/db_pacientes?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
