server.port=8080
spring.application.name=api-gateway

# server.port=8080

# Conexión al servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ==========================================
# CONFIGURACIÓN DE RUTAS CON LOAD BALANCER
# ==========================================

# ==========================================
#                 ms-user
# ==========================================

# Identificador único de la ruta
spring.cloud.gateway.routes[0].id=ms-user-route

# AQUÍ SE IMPLEMENTA EL LOAD BALANCER:
# En lugar de colocar http://localhost:8081, usas lb://nombre-del-servicio
spring.cloud.gateway.routes[0].uri=lb://ms-user

# Condición: Cualquier petición que empiece con /api/users/ pasará por aquí
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# ==========================================
#                 ms-auth
# ==========================================

# Identificador único de la ruta
spring.cloud.gateway.routes[1].id=ms-auth

spring.cloud.gateway.routes[1].uri=lb://ms-auth

spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/** 

# ==========================================
#                 ms-medicos
# ==========================================

# Identificador único de la ruta
spring.cloud.gateway.routes[2].id=ms-medicos

spring.cloud.gateway.routes[2].uri=lb://ms-medicos

spring.cloud.gateway.routes[2].predicates[0]=Path=/api/medicos/**

# ==========================================
#                 ms-pacientes
# ==========================================

spring.cloud.gateway.routes[3].id=ms-pacientes

spring.cloud.gateway.routes[3].uri=lb://ms-pacientes

spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pacientes/**