spring.application.name=ms-urgencias
server.port=8087

# Base de Datos (Se creará automáticamente en XAMPP/MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_urgencias?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/