# 1. Identificación del Microservicio
spring.application.name=ms-facturacion
server.port=8090

# 2. Conexión a la Base de Datos 
spring.datasource.url=jdbc:mysql://localhost:3306/db_hospital_facturacion?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Inicialización y JPA
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Conexión con Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/