spring.application.name=ms-user

# Puerto 
server.port=8081

# Configuración de Base de Datos MySQL (Puerto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/db_user?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# URL donde está escuchando el servidor que acabamos de crear
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



# verificar si soluciona el problema de roles

spring.jpa.hibernate.ddl-auto=update
# O si prefieres mantener los datos:
# spring.jpa.hibernate.ddl-auto=update

# Indicar que queremos ejecutar scripts al iniciar
spring.sql.init.mode=always