spring.application.name=ms-medicos
# Puerto 
server.port=8083

# Configuración de Base de Datos MySQL (Puerto 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/db_medicos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Configuración para el Servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/